version: '2'
services:
  spark-master:
    image: robingu/spark
    ports: 
        - "8080:8080"
        - "7077:7077"
    environment:
        SPARK_MASTER_HOST: spark-master 
    volumes:
        - logs:/opt/spark/logs
    command: ["bin/spark-class", "org.apache.spark.deploy.master.Master"]
    hostname: spark-master

  spark-slave:
    image: robingu/spark
    depends_on:
        - spark-master
    volumes:
        - logs:/opt/spark/logs
    command: ["bin/spark-class", "org.apache.spark.deploy.worker.Worker","spark://spark-master:7077"]
    links:
        - spark-master

    #secondarynamenode:
    #    image: robingu/spark-docker
    #    command: hdfs secondarynamenode
    #    ports:
    #        - "50090:50090"
    #    links:
    #        - namenode:hdfs-namenode
