spark-master:
    image: robingu/spark-docker
    ports: 
        - "8080:8080"
    command: start-master.sh 
    hostname: spark-master

    #datanode:
    #    image: robingu/spark-docker
    #    command: hdfs datanode
    #    ports:
    ## The host port is randomly assigned by Docker, to allow scaling to multiple DataNodes on the same host
    #        - "50075:50075"
    #    links:
    #        - namenode:hdfs-namenode
    #
    #secondarynamenode:
    #    image: robingu/spark-docker
    #    command: hdfs secondarynamenode
    #    ports:
    #        - "50090:50090"
    #    links:
    #        - namenode:hdfs-namenode
