spark-master:
    image: robingu/spark-docker
    ports: 
        - "8080:8080"
    command: start-master.sh 
    hostname: spark-master

spark-slave:
    image: robingu/spark-docker
    command: start-slave.sh 
    #ports:
    #    - "50075:50075"
    links:
        - spark-master:spark-master

    #secondarynamenode:
    #    image: robingu/spark-docker
    #    command: hdfs secondarynamenode
    #    ports:
    #        - "50090:50090"
    #    links:
    #        - namenode:hdfs-namenode
